module.exports = {
    Scripter: [
        { label: "Age", placeholder: "How old are you?" },
        { label: "Timezone", placeholder: "What time zone are you in?" },
        { label: "Activity", placeholder: "How active are you each week?" },
        { label: "Languages", placeholder: "What scripting languages/tools do you know?" },
        { label: "Experience", placeholder: "Do you have previous scripting experience? Share examples." },
        { label: "Production", placeholder: "How would you handle a script that works locally but breaks in production?" },
        { label: "Debugging", placeholder: "Describe a difficult bug you solved." },
        { label: "Git", placeholder: "Are you familiar with Git/version control?" },
        { label: "Reviews", placeholder: "How do you handle code reviews?" },
        { label: "Requirements", placeholder: "What would you do if requirements were unclear?" },
        { label: "Teamwork", placeholder: "Are you comfortable working in a team?" },
        { label: "Why You?", placeholder: "Why should we choose you?" }
    ],

    Builder: [
        { label: "Age", placeholder: "How old are you?" },
        { label: "Timezone", placeholder: "What time zone are you in?" },
        { label: "Activity", placeholder: "How active are you each week?" },
        { label: "Experience", placeholder: "How long have you been building?" },
        { label: "Portfolio", placeholder: "Share your portfolio." },
        { label: "Style", placeholder: "What building style are you best at?" },
        { label: "Optimization", placeholder: "How do you optimize your builds?" },
        { label: "References", placeholder: "How would you recreate a reference image?" },
        { label: "Concept Art", placeholder: "Can you work from concept art?" },
        { label: "Redesign", placeholder: "How do you handle redesign requests?" },
        { label: "Teamwork", placeholder: "Have you worked with scripters before?" },
        { label: "Why You?", placeholder: "Why should we choose you?" }
    ],

    Tester: [
        { label: "Age", placeholder: "How old are you?" },
        { label: "Timezone", placeholder: "What time zone are you in?" },
        { label: "Activity", placeholder: "How active are you each week?" },
        { label: "Experience", placeholder: "Have you tested games before?" },
        { label: "Devices", placeholder: "What devices do you play Roblox on?" },
        { label: "Bug Reports", placeholder: "How do you report bugs clearly?" },
        { label: "Reproducing", placeholder: "What if you can't reproduce a bug?" },
        { label: "Priority", placeholder: "How do you prioritize bugs?" },
        { label: "Documents", placeholder: "Can you use docs/spreadsheets?" },
        { label: "Testing", placeholder: "How do you test new features?" },
        { label: "Feedback", placeholder: "Can you give honest feedback?" },
        { label: "Why You?", placeholder: "Why should we choose you?" }
    ],

"GUI Designer": [
    { label: "Age", placeholder: "How old are you?" },
    { label: "Timezone", placeholder: "What time zone are you in?" },
    { label: "Activity", placeholder: "How active are you each week?" },
    { label: "Software", placeholder: "What software do you use? (Photoshop, Figma, Photopea, etc.)" },
    { label: "Portfolio", placeholder: "Share your portfolio or previous GUI work." },
    { label: "Experience", placeholder: "How long have you been designing interfaces?" },
    { label: "Style", placeholder: "What design style are you most comfortable with?" },
    { label: "UX", placeholder: "How do you make a UI both beautiful and easy to use?" },
    { label: "Feedback", placeholder: "How do you handle feedback on your designs?" },
    { label: "Optimization", placeholder: "How would you optimize a UI for mobile and PC?" },
    { label: "Teamwork", placeholder: "Can you work with builders and scripters?" },
    { label: "Why You?", placeholder: "Why should we choose you?" }
],

Artist: [
    { label: "Age", placeholder: "How old are you?" },
    { label: "Timezone", placeholder: "What time zone are you in?" },
    { label: "Activity", placeholder: "How active are you each week?" },
    { label: "Software", placeholder: "What art software do you use?" },
    { label: "Portfolio", placeholder: "Share your portfolio." },
    { label: "Style", placeholder: "What art style are you best at?" },
    { label: "Best Work", placeholder: "Describe a piece you're proud of." },
    { label: "Revisions", placeholder: "How do you handle revision requests?" },
    { label: "References", placeholder: "Can you work from references?" },
    { label: "Criticism", placeholder: "How do you handle criticism?" },
    { label: "Collaboration", placeholder: "Can you collaborate with other artists?" },
    { label: "Why You?", placeholder: "Why should we choose you?" }
],

"Lead Artist": [
    { label: "Age", placeholder: "How old are you?" },
    { label: "Timezone", placeholder: "What time zone are you in?" },
    { label: "Activity", placeholder: "How active are you each week?" },
    { label: "Experience", placeholder: "How many years have you been making art?" },
    { label: "Portfolio", placeholder: "Share your portfolio." },
    { label: "Leadership", placeholder: "Have you ever led an art team?" },
    { label: "Consistency", placeholder: "How would you keep the team's art style consistent?" },
    { label: "Conflict", placeholder: "How would you resolve disagreements between artists?" },
    { label: "Deadlines", placeholder: "How do you manage deadlines?" },
    { label: "Feedback", placeholder: "How do you give constructive feedback?" },
    { label: "Organization", placeholder: "How do you organize large art projects?" },
    { label: "Why You?", placeholder: "Why should we choose you?" }
],

Video_Editor: [
    { label: "Age", placeholder: "How old are you?" },
    { label: "Timezone", placeholder: "What time zone are you in?" },
    { label: "Activity", placeholder: "How active are you each week?" },
    { label: "Software", placeholder: "What editing software do you use?" },
    { label: "Portfolio", placeholder: "Share your editing portfolio." },
    { label: "Experience", placeholder: "Describe your editing experience." },
    { label: "Content", placeholder: "What type of videos do you enjoy making?" },
    { label: "Engagement", placeholder: "How do you keep videos engaging?" },
    { label: "Audio", placeholder: "Can you sync sound effects and music?" },
    { label: "Deadlines", placeholder: "Can you work under tight deadlines?" },
    { label: "Storyboards", placeholder: "Can you follow storyboards or directions?" },
    { label: "Why You?", placeholder: "Why should we choose you?" }
],
"Voice Actor": [
    { label: "Age", placeholder: "How old are you?" },
    { label: "Timezone", placeholder: "What time zone are you in?" },
    { label: "Activity", placeholder: "How active are you each week?" },
    { label: "Microphone", placeholder: "What microphone/headset do you use?" },
    { label: "Experience", placeholder: "Do you have previous voice acting experience? Share examples." },
    { label: "Languages", placeholder: "What languages and accents can you perform?" },
    { label: "Emotion", placeholder: "How do you portray different emotions in your voice?" },
    { label: "Quality", placeholder: "How do you ensure your recordings have good audio quality?" },
    { label: "Direction", placeholder: "Can you take direction and redo lines if needed?" },
    { label: "Availability", placeholder: "Can you record lines on short notice?" },
    { label: "Teamwork", placeholder: "Can you work closely with writers and directors?" },
    { label: "Why You?", placeholder: "Why should we choose you?" }
],

"Sound Designer": [
    { label: "Age", placeholder: "How old are you?" },
    { label: "Timezone", placeholder: "What time zone are you in?" },
    { label: "Activity", placeholder: "How active are you each week?" },
    { label: "Software", placeholder: "What audio software do you use? (FL Studio, Audition, Reaper, etc.)" },
    { label: "Experience", placeholder: "Describe your sound design experience." },
    { label: "Portfolio", placeholder: "Share examples of your work." },
    { label: "Creation", placeholder: "How do you create immersive sound effects?" },
    { label: "Mixing", placeholder: "How do you balance sounds so they aren't overwhelming?" },
    { label: "Feedback", placeholder: "How do you handle feedback on your audio?" },
    { label: "Deadlines", placeholder: "Can you work under deadlines?" },
    { label: "Teamwork", placeholder: "Can you work with developers and video editors?" },
    { label: "Why You?", placeholder: "Why should we choose you?" }
],

"VFX Artist": [
    { label: "Age", placeholder: "How old are you?" },
    { label: "Timezone", placeholder: "What time zone are you in?" },
    { label: "Activity", placeholder: "How active are you each week?" },
    { label: "Experience", placeholder: "Describe your VFX experience." },
    { label: "Software", placeholder: "What software/tools do you use?" },
    { label: "Portfolio", placeholder: "Share your VFX portfolio." },
    { label: "Optimization", placeholder: "How do you optimize effects for performance?" },
    { label: "Creativity", placeholder: "Describe your favorite VFX you've created." },
    { label: "Style", placeholder: "Can you match an existing art style?" },
    { label: "Feedback", placeholder: "How do you handle revisions?" },
    { label: "Teamwork", placeholder: "Can you work with scripters and artists?" },
    { label: "Why You?", placeholder: "Why should we choose you?" }
],

"Gameplay Designer": [
    { label: "Age", placeholder: "How old are you?" },
    { label: "Timezone", placeholder: "What time zone are you in?" },
    { label: "Activity", placeholder: "How active are you each week?" },
    { label: "Experience", placeholder: "Describe your gameplay design experience." },
    { label: "Favorite Game", placeholder: "What game has your favorite gameplay loop and why?" },
    { label: "Balance", placeholder: "How would you balance an overpowered feature?" },
    { label: "Creativity", placeholder: "Describe an original gameplay mechanic you'd add to a Roblox game." },
    { label: "Testing", placeholder: "How do you test if gameplay is fun?" },
    { label: "Feedback", placeholder: "How do you use player feedback to improve gameplay?" },
    { label: "Teamwork", placeholder: "Can you collaborate with developers and builders?" },
    { label: "Problem Solving", placeholder: "Describe a difficult design problem you've solved." },
    { label: "Why You?", placeholder: "Why should we choose you?" }
],
"Animator": [
    { label: "Discord Username", placeholder: "What is your Discord username?" },
    { label: "Roblox Username", placeholder: "What is your Roblox username?" },
    { label: "Age", placeholder: "How old are you?" },
    { label: "Country", placeholder: "What country are you from?" },
    { label: "Time Zone", placeholder: "What time zone are you in?" },
    { label: "Weekly Hours", placeholder: "How many hours can you contribute each week?" },
    { label: "Languages", placeholder: "What languages do you speak fluently?" },

    { label: "About Yourself", placeholder: "Tell us about yourself." },
    { label: "Why Animator?", placeholder: "Why are you applying for the Animator position?" },
    { label: "Galaxy Games", placeholder: "What interests you about Galaxy Games Inc.?" },
    { label: "Animation Experience", placeholder: "How long have you been animating?" },
    { label: "Previous Projects", placeholder: "Have you worked on any Roblox games or animation projects before? If yes, describe them." },
    { label: "Software", placeholder: "What animation software do you use?" },
    { label: "Portfolio", placeholder: "Please provide your portfolio or examples of your work." },

    { label: "Animation Types", placeholder: "What types of animations are you most experienced with?" },
    { label: "Workflow", placeholder: "Explain your animation workflow from planning to the final product." },
    { label: "Smooth Animations", placeholder: "How do you make animations feel smooth and natural?" },
    { label: "Optimization", placeholder: "How do you optimize animations for Roblox performance?" },
    { label: "Technical Knowledge", placeholder: "Have you worked with animation events, keyframes, or scripting integration? Explain." },

    { label: "Combat Animation", placeholder: "A combat animation feels slow and unresponsive. How would you improve it?" },
    { label: "Last Minute Changes", placeholder: "A developer asks for last-minute changes before an update. How would you handle it?" },
    { label: "Animation Clipping", placeholder: "An animation clips through a weapon or character. How would you fix it?" },
    { label: "Rejected Animation", placeholder: "Your animation is rejected during review. What would you do?" },
    { label: "Animator Disagreement", placeholder: "Two animators disagree on the style of a new animation. How would you resolve the situation?" },
    { label: "Copied Work", placeholder: "You notice another animator copied someone else's work. What would you do?" },

    { label: "Working With Developers", placeholder: "How would you work with Developers?" },
    { label: "Working With VFX", placeholder: "How would you work with VFX Artists?" },
    { label: "Working With Sound Designers", placeholder: "How would you work with Sound Designers?" },
    { label: "Progress Updates", placeholder: "How would you communicate progress on your tasks?" },
    { label: "Constructive Criticism", placeholder: "How do you handle constructive criticism?" },

    { label: "Combat Feel", placeholder: "What makes a combat animation satisfying?" },
    { label: "Elemental Powers", placeholder: "How would you create unique animations for different elemental powers?" },
    { label: "Favorite Game", placeholder: "Which game has your favorite animations, and why?" },
    { label: "Originality", placeholder: "How do you keep your animations original?" },
    { label: "Inspiration", placeholder: "What inspires your animation style?" },

    { label: "Difficult Project", placeholder: "Describe a difficult animation project you completed." },
    { label: "Mistake", placeholder: "Describe a mistake you made and what you learned from it." },
    { label: "Prioritization", placeholder: "How do you prioritize multiple animation requests?" },
    { label: "Missed Deadline", placeholder: "What would you do if you couldn't finish a task before the deadline?" },
    { label: "Quality Standards", placeholder: "How do you ensure your work meets quality standards?" },

    { label: "Why Choose You", placeholder: "Why should Galaxy Games Inc. choose you over other applicants?" },
    { label: "Long-Term Goals", placeholder: "What are your long-term goals as an Animator?" },
    { label: "Preferred Animations", placeholder: "Which type of animations would you like to work on the most?" },
    { label: "Revisions", placeholder: "Are you willing to revise your work based on feedback? Why?" },
    { label: "Final Notes", placeholder: "Is there anything else you would like the Recruitment Team to know?" }
],

"Staff Supervisor": [
    { label: "Discord Username", placeholder: "What is your Discord username?" },
    { label: "Roblox Username", placeholder: "What is your Roblox username?" },
    { label: "Age", placeholder: "How old are you?" },
    { label: "Country", placeholder: "What country are you from?" },
    { label: "Time Zone", placeholder: "What time zone are you in?" },
    { label: "Weekly Hours", placeholder: "How many hours can you contribute each week?" },
    { label: "Languages", placeholder: "What languages do you speak fluently?" },

    { label: "About Yourself", placeholder: "Tell us about yourself." },
    { label: "Why Staff Supervisor?", placeholder: "Why are you applying for Staff Supervisor?" },
    { label: "Galaxy Games", placeholder: "What interests you about Galaxy Games Inc.?" },
    { label: "Leadership Experience", placeholder: "Describe your previous moderation or leadership experience." },
    { label: "Warnings", placeholder: "Have you ever been warned, demoted, or removed from a staff position? Explain." },
    { label: "Proudest Achievement", placeholder: "What achievement are you most proud of as a staff member or leader?" },
    { label: "Trust", placeholder: "Why should we trust you with this position?" },

    { label: "Excellent Supervisor", placeholder: "What qualities make an excellent Staff Supervisor?" },
    { label: "Leadership Style", placeholder: "How would you describe your leadership style?" },
    { label: "Motivation", placeholder: "How do you motivate an inactive staff team?" },
    { label: "Pressure", placeholder: "How do you handle pressure while making important decisions?" },
    { label: "Reputation", placeholder: "How would your previous staff team describe you?" },

    { label: "Abusing Permissions", placeholder: "A moderator is abusing their permissions. What would you do?" },
    { label: "Public Argument", placeholder: "Two moderators begin arguing publicly. How would you resolve the situation?" },
    { label: "Inactive Moderator", placeholder: "A moderator has been inactive for two weeks without notice. What actions would you take?" },
    { label: "Ignoring Management", placeholder: "A staff member continuously ignores management instructions. How would you handle this?" },
    { label: "Wrong Punishment", placeholder: "A moderator accidentally punishes the wrong member. What would you do?" },
    { label: "Confidential Leak", placeholder: "A staff member leaks confidential staff information. Explain your response." },
    { label: "Policy Disagreement", placeholder: "Several moderators disagree with a new staff policy. How would you address their concerns?" },
    { label: "Promotion Request", placeholder: "A Senior Moderator believes they deserve a promotion immediately. How would you respond?" },
    { label: "Disrespectful Moderator", placeholder: "A moderator is an excellent worker but frequently behaves disrespectfully. What would you prioritize?" },
    { label: "Won't Admit Mistake", placeholder: "A moderator refuses to admit they made a mistake. How would you approach the conversation?" },

    { label: "Abuse Report", placeholder: "A member reports staff abuse but provides no evidence. What steps would you take?" },
    { label: "Favoritism Investigation", placeholder: "Multiple members accuse the same moderator of favoritism. How would you investigate?" },
    { label: "Community Insults", placeholder: "A community member publicly insults the moderation team. How would you respond?" },
    { label: "Fair Decisions", placeholder: "How would you ensure moderation decisions remain fair and unbiased?" },
    { label: "Communication", placeholder: "How would you improve communication between staff and the community?" },

    { label: "Community Managers", placeholder: "How would you work alongside Community Managers?" },
    { label: "Developers & Management", placeholder: "How would you work alongside Developers and Management?" },
    { label: "Supervisor Disagreement", placeholder: "How would you handle disagreements with another supervisor?" },
    { label: "Mentoring", placeholder: "How would you mentor a newly promoted moderator?" },
    { label: "Performance Reviews", placeholder: "How would you conduct a performance review for a moderator?" },

    { label: "Difficult Situation", placeholder: "Describe a difficult leadership situation you successfully resolved." },
    { label: "Leadership Mistake", placeholder: "Describe a mistake you made while leading others and what you learned from it." },
    { label: "Prioritization", placeholder: "How do you prioritize multiple responsibilities at once?" },
    { label: "Constructive Criticism", placeholder: "How do you deliver constructive criticism without discouraging staff members?" },
    { label: "Professionalism", placeholder: "How do you maintain professionalism when dealing with disrespectful staff?" },
    { label: "Rejected Recommendation", placeholder: "What would you do if management rejected one of your recommendations?" },

    { label: "Improve Staff Team", placeholder: "What changes would you make to improve our staff team?" },
    { label: "Moderator Standards", placeholder: "What standards should every moderator follow?" },
    { label: "Long-Term Goals", placeholder: "What long-term goals would you have as Staff Supervisor?" },
    { label: "Measure Success", placeholder: "How would you measure whether the moderation team is successful?" },
    { label: "First Month", placeholder: "If selected, what would your first priority be during your first month?" },

    { label: "Why Choose You", placeholder: "Why should Galaxy Games Inc. choose you over other applicants?" },
    { label: "Six Month Goals", placeholder: "What do you hope to accomplish in this role within the next six months?" },
    { label: "Final Notes", placeholder: "Is there anything else you would like the Recruitment Team to know before reviewing your application?" }
],

"Community Manager": [
    { label: "Discord Username", placeholder: "What is your Discord username?" },
    { label: "Roblox Username", placeholder: "What is your Roblox username?" },
    { label: "Age", placeholder: "How old are you?" },
    { label: "Country", placeholder: "What country are you from?" },
    { label: "Time Zone", placeholder: "What time zone are you in?" },
    { label: "Weekly Hours", placeholder: "How many hours can you contribute each week?" },
    { label: "Languages", placeholder: "What languages do you speak fluently?" },

    { label: "About Yourself", placeholder: "Tell us about yourself." },
    { label: "Why Community Manager?", placeholder: "Why are you applying for the Community Manager position?" },
    { label: "Galaxy Games", placeholder: "What interests you about Galaxy Games Inc.?" },
    { label: "Studio Knowledge", placeholder: "What do you know about our studio?" },
    { label: "Experience", placeholder: "Describe any previous community management experience. Include the server, your role, and how long you served." },
    { label: "Proudest Achievement", placeholder: "What achievement are you most proud of in a community or leadership role?" },
    { label: "Trust", placeholder: "Why should we trust you with this role?" },

    { label: "Excellent Community Manager", placeholder: "What qualities make an exceptional Community Manager?" },
    { label: "Leadership Style", placeholder: "How would you describe your leadership style?" },
    { label: "Motivating Community", placeholder: "How do you motivate a community during slow periods?" },
    { label: "Pressure", placeholder: "How do you remain calm under pressure?" },
    { label: "Reputation", placeholder: "How would your previous teammates describe you?" },

    { label: "Helping New Players", placeholder: "A new player joins the server and has many questions. What would you do?" },
    { label: "Public Argument", placeholder: "Two members begin arguing publicly. How would you handle the situation?" },
    { label: "Negative Member", placeholder: "A member repeatedly spreads negativity about the game. What actions would you take?" },
    { label: "Bug Report", placeholder: "A player reports a bug while insulting the developers. How would you respond?" },
    { label: "Leaving Community", placeholder: "A respected community member begins encouraging others to leave the server. What would you do?" },
    { label: "Update Criticism", placeholder: "An update receives significant criticism from the community. How would you communicate with players?" },
    { label: "Staff Misconduct", placeholder: "A moderator is behaving unprofessionally toward members. How would you handle the situation?" },
    { label: "Developer Mistake", placeholder: "A developer accidentally shares incorrect information. How would you manage the confusion?" },
    { label: "Favoritism", placeholder: "Several players accuse a staff member of favoritism. What steps would you take before reaching a conclusion?" },
    { label: "Content Creator", placeholder: "A content creator complains publicly about your moderation team. How would you respond?" },

    { label: "Community Events", placeholder: "What types of community events would you organize?" },
    { label: "Increase Activity", placeholder: "How would you increase server activity?" },
    { label: "Attract Players", placeholder: "How would you attract new players to the game?" },
    { label: "Retain Members", placeholder: "How would you retain long-term members?" },
    { label: "Collect Feedback", placeholder: "How would you collect and organize player feedback?" },
    { label: "Present Feedback", placeholder: "How would you present community feedback to the developers?" },
    { label: "Encourage Participation", placeholder: "How would you encourage players to participate in announcements, polls, and events?" }
],

"Event Manager": [
    { label: "Discord Username", placeholder: "What is your Discord username?" },
    { label: "Age", placeholder: "How old are you?" },
    { label: "Time Zone", placeholder: "What time zone are you in?" },
    { label: "Weekly Activity", placeholder: "How active are you each week?" },
    { label: "Event Team Experience", placeholder: "How long have you been part of the Event team, and what have you contributed so far?" },

    { label: "Management Experience", placeholder: "Do you have previous experience managing an event team (not just hosting events yourself)? Please give specific examples." },
    { label: "Overseeing Directors", placeholder: "Have you ever overseen multiple Event Directors or Assistant Directors at once? What was that like?" },
    { label: "Manager vs Director", placeholder: "What do you think separates an Event Manager from an Event Director?" },
    { label: "Biggest Team", placeholder: "What's the biggest event or event team you've ever been responsible for?" },

    { label: "Building Trust", placeholder: "How do you build trust with Event Directors who don't know you yet?" },
    { label: "Team Morale", placeholder: "How do you keep morale up on the event team after a poorly received or failed event?" },
    { label: "Onboarding", placeholder: "How would you onboard a new Event Director so they run their first event successfully?" },
    { label: "Healthy Team", placeholder: "What does a healthy, motivated event team look like to you?" },

    { label: "Scheduling Events", placeholder: "How would you keep multiple Event Directors aligned when they're running events in the same week?" },
    { label: "Conflict Resolution", placeholder: "Two Event Directors want the same time slot or resources for their events. How do you resolve it?" },
    { label: "Missed Deadlines", placeholder: "How would you handle an Event Director who keeps missing deadlines or under-delivering?" },
    { label: "Approving Events", placeholder: "How do you decide which event ideas get greenlit, postponed, or cut entirely?" },
    { label: "Smaller Events", placeholder: "How do you make sure smaller events don't get overshadowed by bigger ones?" },

    { label: "Progress Tracking", placeholder: "How would you track event preparation across multiple Directors without micromanaging?" },
    { label: "No Updates", placeholder: "What would you do if an Event Director hasn't given any updates in the days leading up to their event?" },
    { label: "Accountability", placeholder: "How do you hold an Event Director accountable without discouraging them?" },
    { label: "Enforcing Deadlines", placeholder: "Are you comfortable setting and enforcing preparation deadlines for events you're not personally running?" }
],

"Media Manager": [
    { label: "Discord Username", placeholder: "What is your Discord username?" },
    { label: "Roblox Username", placeholder: "What is your Roblox username?" },
    { label: "Age", placeholder: "How old are you?" },
    { label: "Country", placeholder: "What country are you from?" },
    { label: "Time Zone", placeholder: "What time zone are you in?" },
    { label: "Weekly Hours", placeholder: "How many hours can you contribute each week?" },
    { label: "Languages", placeholder: "What languages do you speak fluently?" },

    { label: "About Yourself", placeholder: "Tell us about yourself." },
    { label: "Why Media Manager?", placeholder: "Why are you applying for the Media Manager position?" },
    { label: "Galaxy Games", placeholder: "What interests you about Galaxy Games Inc.?" },
    { label: "Media Experience", placeholder: "Describe your previous experience in media, marketing, content creation, or community promotion." },
    { label: "Best Projects", placeholder: "What media projects are you most proud of?" },
    { label: "Trust", placeholder: "Why should we trust you with this role?" },

    { label: "Main Responsibility", placeholder: "What do you believe is the primary responsibility of a Media Manager?" },
    { label: "Brand Identity", placeholder: "How would you maintain a consistent brand identity across all platforms?" },
    { label: "Social Media", placeholder: "What social media platforms should Galaxy Games Inc. focus on, and why?" },
    { label: "Increase Engagement", placeholder: "How would you increase engagement on our social media accounts?" },
    { label: "Campaign Success", placeholder: "How would you measure whether a media campaign was successful?" },

    { label: "No Updates", placeholder: "Development has slowed and there are no major updates for several weeks. How would you keep the community engaged?" },
    { label: "Negative Trailer", placeholder: "A trailer receives negative feedback shortly after release. How would you respond?" },
    { label: "False Information", placeholder: "A creator posts false information about the game that begins spreading quickly. What would you do?" },
    { label: "Developer Leak", placeholder: "A developer accidentally shares confidential information publicly. How would you handle the situation?" },
    { label: "Fan Content", placeholder: "A community member creates impressive fan content. How would you use it to benefit the community while respecting the creator?" },
    { label: "Wrong Announcement", placeholder: "A scheduled announcement contains incorrect information after being published. What actions would you take?" },
    { label: "Delayed Update", placeholder: "You are asked to announce a delayed update. How would you write the announcement while maintaining player confidence?" },
    { label: "Feature Reveal", placeholder: "The development team wants to reveal a new feature. How would you build anticipation before the announcement?" },

    { label: "Content Planning", placeholder: "Describe your process for planning a month's worth of content." },
    { label: "Announcement Frequency", placeholder: "How often should announcements be posted?" },
    { label: "Best Content", placeholder: "What types of content generate the highest engagement for Roblox communities?" },
    { label: "Organizing Media", placeholder: "How would you organize screenshots, trailers, and promotional artwork?" },
    { label: "Working With Team", placeholder: "How would you coordinate with the Video Director and Social Media Manager?" },

    { label: "Developers", placeholder: "How would you work alongside Developers?" },
    { label: "Community Manager", placeholder: "How would you work alongside the Community Manager?" },
    { label: "Creative Director", placeholder: "How would you work alongside the Creative Director?" },
    { label: "Team Disagreements", placeholder: "How would you handle disagreements within the media team?" },
    { label: "Rejected Idea", placeholder: "What would you do if management rejected one of your campaign ideas?" },

    { label: "Difficult Project", placeholder: "Describe a difficult project you completed successfully." },
    { label: "Mistake", placeholder: "Describe a mistake you made and what you learned from it." },
    { label: "Deadlines", placeholder: "How do you prioritize multiple deadlines?" },
    { label: "Criticism", placeholder: "How do you handle criticism of your work?" },
    { label: "Accuracy", placeholder: "How do you ensure accuracy before publishing announcements?" },
    { label: "Confidential Files", placeholder: "What would you do if confidential media files were accidentally leaked?" },

    { label: "Public Image", placeholder: "What improvements would you make to Galaxy Games Inc.'s public image?" },
    { label: "Marketing Strategy", placeholder: "Describe your ideal marketing strategy for a Roblox game launch." },
    { label: "Stand Out", placeholder: "How would you help Galaxy Games Inc. stand out from other Roblox studios?" },
    { label: "Three Month Goals", placeholder: "What goals would you set during your first three months as Media Manager?" },
    { label: "Long-Term Vision", placeholder: "What long-term vision do you have for our media presence?" },

    { label: "Why Choose You", placeholder: "Why should Galaxy Games Inc. choose you over other applicants?" },
    { label: "Portfolio", placeholder: "Please provide examples of your previous work (portfolio, YouTube channel, social media accounts, graphics, trailers, etc.)." },
    { label: "Final Notes", placeholder: "Is there anything else you would like the Recruitment Team to know before reviewing your application?" }
],
};

    
